### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mccolljr** [grubby/grubby#5]
I'm interested in contributing, but the last commits were all in 2015.
It appears as though this is no longer maintained. Is that the case?

**Comment by tjarratt** [comment]
I think about Grubby a bit most days, but I haven't had cause or much time to really continue contributing to the project.

My initial goal was to continue learning about Ruby and Go while simultaneously learning more about how highly dynamic, interpreted languages (such as Ruby) as implemented. In that respect, this project was a huge success.

With all that said ... I'd also like for it to possibly become a fully baked ruby implementation, but I don't really have the time to drive that any more.

I do know that @andrewarrow is interested in contributing, and has started to work on some issues [on his own personal fork](https://github.com/andrewarrow/grubby).

I'd be happy to review PRs, promote contributors, provide any guidance and occasionally contribute back, but I have...

* a full time job as an engineer at a very demanding consultancy
* additional responsibilities as a manager
* several other burning hot open source projects to maintain and work on
* a two year old that demands more and more of my time each day

Given all of those constraints, how can I best help you @mccolljr ? Would it be helpful if I took all of my existing tasks out of a text document on my hard drive and turned them into github issues so they could be tackled by yourself and others?

The biggest task I wanted to tackle next was really getting the rubyspec tests to actually run for grubby. The last ~100 or so commits are all incremental improvements on getting various parts of the rubyspec infrastructure to not fall over because some method or such was not implemented.

**Comment by mccolljr** [comment]
I'm sorry it's taken me a week to reply.
I've also been quite busy with work, as I'm managing the development of 2 new applications within our office.

To help frame what I'm asking for, there are a couple of reasons I'd like to contribute to a Ruby implementation in Go,
- When I went through the MRI source code it piqued my interest. I was curious if a similar approach was possible in Go. I began a personal implementation in Go, but Grubby is more mature, and has many more features already present.
- I would like see a Ruby implementation that can take advantage of Go's concurrency primitives

I've gone through the code, but a brief high-level explanation of your implementation's structure would reduce my onboading time. It will help me visualize the structure at a higher level.

If you would be willing to send me that text file containing the existing tasks, that would also be great. I won't ask you to open them all as issues.

Thanks,

Jake

**Comment by johnny-morrice** [comment]
Drive-by vote to upload text task file as comment in this thread so that community can see.

**Comment by cptfoo** [comment]
Love to see this as the engine for a replacement Unix/bash shell that uses ruby or a limited ruby to replace bash. This project a good fit?

**Comment by tjarratt** [comment]
This could be an interesting fit @cptfoo, but I'm not sure why you wouldn't just go with MRI ruby, or one of the other implementations.

If you wanted to use something new and shiny, you could also use [grumpy](https://github.com/google/grumpy).

Grubby isn't a bad project, but it's a very large undertaking and while I was able to easily dedicate about 30-60 minutes a night to coding and making progress on getting rubyspec to pass, now that my son is older I'm finding it harder to do that (combined with more responsibility at work).

**Comment by lostinblue** [comment]
This is a really interesting project, I like being able to read through the parser code and just get it. 

I think the advantage over MRI would be having everything built in a single language. Not having to rely on MRI binaries to not be tampered with too.

**Comment by lostinblue** [comment]
If I wanted to contribute and start adding methods to string, like .class, .methods, .reverse, etc 

Can you explain where I would start and what files I would focus on? 

Thanks for all the work you have put into this, I totally understand having less time.

**Comment by tjarratt** [comment]
Hey @lostinblue thank you SO MUCH for the kind words. Research shows that once you read some negative feedback on the internet, it takes 10 more instances of positive feedback for you to feel it balances out.

Luckily, I only read your positive feedback today, so now I feel great!

If you wanted to add methods such as `#class` and `#methods` and `#reverse`, where to start... that's a great question. Let's start with `#reverse`.

Open up `vm/array_test.go`. Write a spec that captures the behavior you think is important. Try to keep it small and simple. Jump down into `vm/builtins/array.go` and look where the builtin methods are added. There's probably a big section that just defines those in the file. Looking back now, I'm not THRILLED WITH MYSELF w.r.t. how I organized this, but that's how it is right now. Define a new method that you think implements the behavior correctly. Try to leverage TDD and red-green-refactor to iterate towards the correct solution. Feel free to define more unit level tests, if you find it helps to drive a better, more correct implementation.

That's it for `#reverse`. In my mind, `#class` and `#methods` feel harder, but I suppose it's not. Here's a short list of steps I would take for those.

* fire up MRI's irb and run `method(:class)` or `method(:methods)` -- keep track of which class or module defines these
* poke around in grubby's `interpreter/vm/builtins` directory and see if that module or class is defined
* start by defining it - I often copy-pasta'd another, small implementation and then removed anything irrelevant to the class I was defining
* write a small test for the behavior you want to see
* write some simple, naive code that makes that test pass
* continue previous steps, refactoring until you are happy
* BAM, you just wrote a feature. Commit!

Hope you find these loose, adhoc instructions helpful!

**Comment by tmc** [comment]
@tjarratt those are great instructions. Could you put them into a contributing.md file?

**Comment by tjarratt** [comment]
You got it @tmc - your wish is my command.
